[package]
name = "linux-desk"
version = "0.1.0"
edition = "2024"
author = ["Al-ameen"]

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
dirs = "6.0.0"

[target.'cfg(target_os = "linux")'.dependencies]
# Add dependencies specific to Linux here if needed